import Head from "next/head";
import { Fragment, useContext } from "react";
import AuthContext from "../store/auth-context";
import Welcome from "../components/UI/Welcome";

export default function Home() {
  const authCtx = useContext(AuthContext);
  const isLoggedIn = authCtx.isLoggedIn;

  return (
    <Fragment>
      <Head>
        <title>Foodie | What are you cooking?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!isLoggedIn && <Welcome />}
    </Fragment>
  );
}
